### ISSUE TITLE
Regarding usage of this pkg to generate contour lines on an image.

### ISSUE THREAD

**Issue by sparshgarg23** [kakearney/contourfcmap-pkg#5]
Hi,don't know if you still keep track of the issues but here goes.
The function accepts x,y and z as input arguments.
Let's say I have an image of dimension 71x61,then how should I feed  that image as an input to the function.
Also I would like to extract the contours at a specific level for further processing,
for example in matlab contourf I can generate contour a say level 240,the output of this is a matrix of 2xN dimension which indicates the points that make up the contour at that level,any idea on how I can do the same using this package.
Thanks and I hope to hear from you soon.
Also,currently the contour I am getting from contourf tends to have a straight line running from one end to another as shown in the below image.Any reason why this is happening.
![my_output_from_contourf](https://user-images.githubusercontent.com/34626942/124769375-0c831c80-df57-11eb-8228-58a5e94af5fd.png)

**Comment by kakearney** [comment]
How to contour an image without x/y coordinates: To mimic the behavior of contour/contourf/etc. with a single input, set x = 1:size(z,2) and y = 1:size(z,1) (where z is your 71 x 61 image matrix).

Extracting contours: The 2xN contour matrix is returned in the c field of the output structure.

Straight line at bottom: I can't hypothesize on this without actually seeing your data.
